let dados = [
    {
        nome: "Catan",
        editora: "Kosmos",
        descricao: "Um clássico jogo de estratégia onde você constrói e desenvolve sua civilização enquanto compete por recursos.",
        numeroJogadores: { min: 3, max: 4 },
        idadeRecomendada: 10,
        tempoMedio: "60-90 minutos",
        mecanicas: ["construção", "negociação", "coleta de recursos"],
        complexidade: "média",
        avaliacao: 9,
        tags: ["estratégia", "negociação", "recursos", "família", "jogo de tabuleiro"]
    },
    {
        nome: "Ticket to Ride",
        editora: "Days of Wonder",
        descricao: "Construa rotas de trem através dos Estados Unidos e complete cartões de destino para ganhar pontos.",
        numeroJogadores: { min: 2, max: 5 },
        idadeRecomendada: 8,
        tempoMedio: "30-60 minutos",
        mecanicas: ["construção de rotas", "coleta de cartas"],
        complexidade: "baixa",
        avaliacao: 8.8,
        tags: ["estratégia", "trens", "família", "jogo de tabuleiro"]
    },
    {
        nome: "Carcassonne",
        editora: "Z-Man Games",
        descricao: "Coloque peças de terreno e coloque seus seguidores para ganhar controle de cidades, estradas e campos.",
        numeroJogadores: { min: 2, max: 5 },
        idadeRecomendada: 7,
        tempoMedio: "35-45 minutos",
        mecanicas: ["colocação de peças", "controle de área"],
        complexidade: "baixa",
        avaliacao: 8.5,
        tags: ["estratégia", "colocação de peças", "controle de área", "família", "jogo de tabuleiro"]
    },
    {
        nome: "Pandemic",
        editora: "Z-Man Games",
        descricao: "Trabalhe em equipe para erradicar doenças e salvar o mundo antes que seja tarde demais.",
        numeroJogadores: { min: 2, max: 4 },
        idadeRecomendada: 8,
        tempoMedio: "45-60 minutos",
        mecanicas: ["cooperativo", "gestão de recursos"],
        complexidade: "média",
        avaliacao: 9,
        tags: ["cooperativo", "estratégia", "temático", "jogo de tabuleiro"]
    },
    {
        nome: "Codenames",
        editora: "Czech Games Edition",
        descricao: "Dê pistas para sua equipe adivinhar palavras codificadas antes da equipe adversária.",
        numeroJogadores: { min: 2, max: 8 },
        idadeRecomendada: 14,
        tempoMedio: "15-30 minutos",
        mecanicas: ["dedução", "palavras"],
        complexidade: "baixa",
        avaliacao: 8.6,
        tags: ["party game", "dedução", "comunicação", "estratégia", "jogo de tabuleiro"]
    },
    {
        nome: "7 Wonders",
        editora: "Repos Production",
        descricao: "Desenvolva sua civilização e construa maravilhas para ganhar pontos de vitória através das eras.",
        numeroJogadores: { min: 2, max: 7 },
        idadeRecomendada: 10,
        tempoMedio: "30 minutos",
        mecanicas: ["cartas", "construção de civilização"],
        complexidade: "média",
        avaliacao: 9,
        tags: ["estratégia", "civilização", "cartas", "jogo de tabuleiro"]
    },
    {
        nome: "Azul",
        editora: "Plan B Games",
        descricao: "Complete padrões e construa mosaicos com peças coloridas em um jogo de estratégia e estética.",
        numeroJogadores: { min: 2, max: 4 },
        idadeRecomendada: 8,
        tempoMedio: "30-45 minutos",
        mecanicas: ["colocação de peças", "padrões"],
        complexidade: "baixa",
        avaliacao: 8.7,
        tags: ["abstrato", "estratégia", "família", "jogo de tabuleiro", "padrões"]
    },
    {
        nome: "Gloomhaven",
        editora: "Cephalofair Games",
        descricao: "Um jogo de aventura cooperativo e em campanha com exploração e combate tático.",
        numeroJogadores: { min: 1, max: 4 },
        idadeRecomendada: 14,
        tempoMedio: "60-120 minutos",
        mecanicas: ["cooperativo", "campanha", "exploração"],
        complexidade: "alta",
        avaliacao: 9.4,
        tags: ["cooperativo", "aventura", "fantasia", "alta complexidade", "jogo de tabuleiro"]
    },
    {
        nome: "Betrayal at House on the Hill",
        editora: "Avalon Hill",
        descricao: "Explore uma mansão assombrada e descubra segredos enquanto um jogador se torna o traidor.",
        numeroJogadores: { min: 3, max: 6 },
        idadeRecomendada: 12,
        tempoMedio: "60-90 minutos",
        mecanicas: ["exploração", "temático", "traição"],
        complexidade: "média",
        avaliacao: 8.5,
        tags: ["horror", "temático", "exploração", "jogo de tabuleiro", "traição"]
    },
    {
        nome: "Splendor",
        editora: "Space Cowboys",
        descricao: "Adquira gemas e cartas para construir seu império comercial e ganhar a maior quantidade de pontos.",
        numeroJogadores: { min: 2, max: 4 },
        idadeRecomendada: 10,
        tempoMedio: "30 minutos",
        mecanicas: ["coleção de cartas", "economia"],
        complexidade: "baixa",
        avaliacao: 8.6,
        tags: ["estratégia", "coleção de cartas", "jogo de tabuleiro", "economia"]
    },
    {
        nome: "Secret Hitler",
        editora: "Big Potato Games",
        descricao: "Um jogo de dedução e engano onde os jogadores tentam descobrir quem é o Secret Hitler antes que seja tarde demais.",
        numeroJogadores: { min: 5, max: 10 },
        idadeRecomendada: 12,
        tempoMedio: "45 minutos",
        mecanicas: ["dedução", "engano", "partido político"],
        complexidade: "média",
        avaliacao: 8.7,
        tags: ["dedução", "engano", "party game", "jogo de tabuleiro", "política"]
    },
    {
        nome: "Love Letter",
        editora: "Z-Man Games",
        descricao: "Use dedução e estratégia para entregar sua carta à princesa e ganhar seu favor.",
        numeroJogadores: { min: 2, max: 4 },
        idadeRecomendada: 10,
        tempoMedio: "20 minutos",
        mecanicas: ["dedução", "cartas"],
        complexidade: "baixa",
        avaliacao: 8.5,
        tags: ["estratégia", "dedução", "jogo de cartas", "rápido", "jogo de tabuleiro"]
    },
    {
        nome: "Viticulture",
        editora: "Stonemaier Games",
        descricao: "Gerencie uma vinícola e produza vinhos para conquistar o maior número de pontos de vitória.",
        numeroJogadores: { min: 1, max: 6 },
        idadeRecomendada: 14,
        tempoMedio: "45-90 minutos",
        mecanicas: ["gestão de trabalhadores", "economia", "temático"],
        complexidade: "média",
        avaliacao: 8.7,
        tags: ["estratégia", "vinho", "gestão de recursos", "jogo de tabuleiro"]
    },
    {
        nome: "The Crew",
        editora: "Kosmos",
        descricao: "Trabalhe com sua equipe para completar missões no espaço, resolvendo desafios de cartas ao longo do caminho.",
        numeroJogadores: { min: 2, max: 4 },
        idadeRecomendada: 10,
        tempoMedio: "20-60 minutos",
        mecanicas: ["cooperativo", "jogo de cartas", "missões"],
        complexidade: "média",
        avaliacao: 8.6,
        tags: ["cooperativo", "estratégia", "jogo de cartas", "missões", "jogo de tabuleiro"]
    },
    {
        nome: "Decrypto",
        editora: "IELLO",
        descricao: "Tente codificar e decifrar mensagens para vencer sua equipe adversária.",
        numeroJogadores: { min: 3, max: 8 },
        idadeRecomendada: 12,
        tempoMedio: "30 minutos",
        mecanicas: ["dedução", "palavras"],
        complexidade: "baixa",
        avaliacao: 8.7,
        tags: ["dedução", "estratégia", "party game", "jogo de tabuleiro", "comunicação"]
    },
    {
        nome: "Root",
        editora: "Leader Games",
        descricao: "Controle uma facção diferente em uma luta pelo controle da floresta, cada uma com suas próprias estratégias e mecânicas.",
        numeroJogadores: { min: 2, max: 4 },
        idadeRecomendada: 10,
        tempoMedio: "60-90 minutos",
        mecanicas: ["controle de área", "gestão de mão", "assimétrico"],
        complexidade: "alta",
        avaliacao: 9,
        tags: ["estratégia", "controle de área", "fantasia", "jogo de tabuleiro"]
    },
    {
        nome: "Blood Rage",
        editora: "Cool Mini or Not",
        descricao: "Lidere uma facção viking em batalhas épicas e conquiste territórios para ganhar glória antes do Ragnarok.",
        numeroJogadores: { min: 2, max: 4 },
        idadeRecomendada: 14,
        tempoMedio: "60-90 minutos",
        mecanicas: ["conflito", "controle de área", "gestão de cartas"],
        complexidade: "alta",
        avaliacao: 8.9,
        tags: ["estratégia", "conflito", "mitologia", "jogo de tabuleiro"]
    },
    {
        nome: "Agricola",
        editora: "Z-Man Games",
        descricao: "Administre sua fazenda, plantando e criando animais para garantir o crescimento e a prosperidade da sua família.",
        numeroJogadores: { min: 1, max: 5 },
        idadeRecomendada: 12,
        tempoMedio: "30-150 minutos",
        mecanicas: ["gestão de recursos", "gestão de trabalhadores"],
        complexidade: "alta",
        avaliacao: 8.8,
        tags: ["estratégia", "gestão de recursos", "fazenda", "jogo de tabuleiro"]
    },
    {
        nome: "Everdell",
        editora: "Starling Games",
        descricao: "Construa e desenvolva uma cidade de criaturas em um mundo de fantasia com mecânicas de colocação de trabalhadores e coleção de cartas.",
        numeroJogadores: { min: 1, max: 4 },
        idadeRecomendada: 10,
        tempoMedio: "40-80 minutos",
        mecanicas: ["gestão de trabalhadores", "coleção de cartas", "fantasia"],
        complexidade: "média",
        avaliacao: 8.8,
        tags: ["fantasia", "estratégia", "gestão de trabalhadores", "jogo de tabuleiro"]
    },
    {
        nome: "Spirit Island",
        editora: "Greater Than Games",
        descricao: "Defenda sua ilha de invasores estrangeiros em um jogo cooperativo de estratégia com alta complexidade.",
        numeroJogadores: { min: 1, max: 4 },
        idadeRecomendada: 13,
        tempoMedio: "90-120 minutos",
        mecanicas: ["cooperativo", "controle de área", "estratégia"],
        complexidade: "alta",
        avaliacao: 9.2,
        tags: ["cooperativo", "estratégia", "temático", "jogo de tabuleiro", "alta complexidade"]
    }
];
